"""drop_person_debug_table

Revision ID: 38ae744f3444
Revises: bf7bcd7c1293
Create Date: 2026-07-02 14:50:37.779083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '38ae744f3444'
down_revision: Union[str, None] = 'bf7bcd7c1293'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_person_debug_camera_id', table_name='person_debug')
    op.drop_index('ix_person_debug_failure_stage', table_name='person_debug')
    op.drop_index('ix_person_debug_occurred_at', table_name='person_debug')
    op.drop_index('ix_person_debug_person_identity_id', table_name='person_debug')
    op.drop_index('ix_person_debug_reid_success', table_name='person_debug')
    op.drop_index('ix_person_debug_store_id', table_name='person_debug')
    op.drop_index('ix_person_debug_track_session_id', table_name='person_debug')
    op.drop_table('person_debug')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person_debug',
    sa.Column('camera_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('store_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('track_session_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('person_identity_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('occurred_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('reid_attempted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('reid_success', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('bbox_height_px', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('bbox_width_px', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('detection_confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('track_total_frames', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('track_age_seconds', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('crop_path', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('body_crop_path', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('crop_height_px', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('crop_width_px', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quality_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('quality_passed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('keypoint_visibility_ratio', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('keypoint_gate_passed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('sharpness_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('size_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('aspect_ratio', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('brightness_mean', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('face_detected', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('face_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('face_crop_path', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('face_age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('face_gender', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('reid_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('reid_confident', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('reid_frame_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('failure_stage', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('failure_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], name='person_debug_camera_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['person_identity_id'], ['person_identities.id'], name='person_debug_person_identity_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name='person_debug_store_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['track_session_id'], ['track_sessions.id'], name='person_debug_track_session_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='person_debug_pkey')
    )
    op.create_index('ix_person_debug_track_session_id', 'person_debug', ['track_session_id'], unique=False)
    op.create_index('ix_person_debug_store_id', 'person_debug', ['store_id'], unique=False)
    op.create_index('ix_person_debug_reid_success', 'person_debug', ['reid_success'], unique=False)
    op.create_index('ix_person_debug_person_identity_id', 'person_debug', ['person_identity_id'], unique=False)
    op.create_index('ix_person_debug_occurred_at', 'person_debug', ['occurred_at'], unique=False)
    op.create_index('ix_person_debug_failure_stage', 'person_debug', ['failure_stage'], unique=False)
    op.create_index('ix_person_debug_camera_id', 'person_debug', ['camera_id'], unique=False)
    # ### end Alembic commands ###
