"""Add best_crop_path to TrackSession

Revision ID: 8b8b559916d9
Revises: b872230f22bc
Create Date: 2026-06-13 15:20:13.510172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '8b8b559916d9'
down_revision: Union[str, None] = 'b872230f22bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('track_sessions', sa.Column('best_crop_path', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('track_sessions', 'best_crop_path')
    # ### end Alembic commands ###
