"""Add best_crop_path to TrackSession

Revision ID: 8b8b559916d9
Revises: b872230f22bc
Create Date: 2026-06-13 15:20:13.510172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '8b8b559916d9'
down_revision: Union[str, None] = 'b872230f22bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _column_exists(table: str, column: str) -> bool:
    """Check if a column exists in a table"""
    from sqlalchemy import inspect
    
    conn = op.get_bind()
    inspector = inspect(conn)
    
    # Get all columns for the table
    try:
        columns = [col['name'] for col in inspector.get_columns(table)]
        return column in columns
    except Exception:
        # Fallback to raw SQL if inspector fails
        try:
            result = conn.execute(
                sa.text(
                    "SELECT EXISTS ("
                    "SELECT 1 FROM information_schema.columns "
                    "WHERE table_name = :table AND column_name = :column"
                    ")"
                ),
                {"table": table, "column": column},
            )
            return result.scalar()
        except Exception:
            # If both methods fail, assume column doesn't exist
            return False


def upgrade() -> None:
    if _column_exists("track_sessions", "best_crop_path"):
        return

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('track_sessions', sa.Column('best_crop_path', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    if not _column_exists("track_sessions", "best_crop_path"):
        return

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('track_sessions', 'best_crop_path')
    # ### end Alembic commands ###
