"""Add person_face_embeddings table

Revision ID: b872230f22bc
Revises: 0003_demographics_rotation
Create Date: 2026-06-13 14:55:09.347854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = 'b872230f22bc'
down_revision: Union[str, None] = '0003_demographics_rotation'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person_face_embeddings',
    sa.Column('person_identity_id', sa.UUID(), nullable=False),
    sa.Column('embedding', Vector(dim=512), nullable=False),
    sa.Column('camera_id', sa.UUID(), nullable=True),
    sa.Column('face_score', sa.Float(), nullable=False),
    sa.Column('face_crop_path', sa.String(length=500), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ),
    sa.ForeignKeyConstraint(['person_identity_id'], ['person_identities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_person_face_embeddings_person_identity_id'), 'person_face_embeddings', ['person_identity_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_person_face_embeddings_person_identity_id'), table_name='person_face_embeddings')
    op.drop_table('person_face_embeddings')
    # ### end Alembic commands ###
