"""make_zones_independent_and_assign_to_camera

Revision ID: d02b913dd571
Revises: 0002_perf_indexes
Create Date: 2026-06-12 17:58:42.665979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = 'd02b913dd571'
down_revision: Union[str, None] = '0002_perf_indexes'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cameras', sa.Column('zone_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'cameras', 'zones', ['zone_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('zones_camera_view_id_fkey', 'zones', type_='foreignkey')
    op.drop_column('zones', 'camera_view_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zones', sa.Column('camera_view_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('zones_camera_view_id_fkey', 'zones', 'camera_views', ['camera_view_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'cameras', type_='foreignkey')
    op.drop_column('cameras', 'zone_id')
    # ### end Alembic commands ###
