"""Rule evaluator - evaluates rules against track state in memory."""

import uuid
from datetime import datetime
from typing import Dict, List, Optional
from dataclasses import dataclass, field

from loguru import logger

from app.utils.geometry import line_crossing_check, line_from_json, bbox_bottom_center
from app.utils.time_utils import utc_now, is_within_cooldown
from app.modules.tracking.track_manager import ActiveTrack


@dataclass
class RuleEvent:
    """Event generated by rule evaluation."""
    rule_id: uuid.UUID
    rule_type: str
    camera_id: uuid.UUID
    zone_id: Optional[uuid.UUID]
    track_session_id: Optional[uuid.UUID]
    person_identity_id: Optional[uuid.UUID]
    event_type: str
    severity: str
    description: str
    metadata: dict = field(default_factory=dict)


class RuleCache:
    """In-memory cache for active rules. Reloaded on demand."""

    def __init__(self):
        self.rules: List[dict] = []
        self.zones: Dict[str, dict] = {}
        self.last_loaded: Optional[datetime] = None

    def load(self, rules: List[dict], zones: Dict[str, dict]):
        self.rules = rules
        self.zones = zones
        self.last_loaded = utc_now()
        logger.info(f"Rule cache loaded: {len(rules)} rules, {len(zones)} zones")

    def get_rules_for_camera(self, camera_id: uuid.UUID) -> List[dict]:
        return [r for r in self.rules if r.get("camera_id") is None or str(r["camera_id"]) == str(camera_id)]


class RuleEvaluator:
    """Evaluates rules against active tracks per frame."""

    def __init__(self):
        self.cache = RuleCache()
        self._cooldown_tracker: Dict[str, datetime] = {}  # rule_id+track_id -> last_event_time
        self._last_prune: datetime = utc_now()
        self._prune_interval_seconds: float = 60.0

    def _prune_cooldowns(self):
        """Remove expired cooldown entries so the tracker doesn't grow forever."""
        now = utc_now()
        if (now - self._last_prune).total_seconds() < self._prune_interval_seconds:
            return
        self._last_prune = now

        max_cooldown = max(
            (r.get("cooldown_seconds", 30) for r in self.cache.rules), default=30
        )
        cutoff_seconds = max(max_cooldown, 300)  # keep at least 5 min of history
        before = len(self._cooldown_tracker)
        self._cooldown_tracker = {
            k: v
            for k, v in self._cooldown_tracker.items()
            if (now - v).total_seconds() < cutoff_seconds
        }
        removed = before - len(self._cooldown_tracker)
        if removed:
            logger.debug(f"Cooldown tracker pruned: removed {removed} expired entries")

    def evaluate(self, camera_id: uuid.UUID, tracks: List[ActiveTrack], camera_role: str = "general",
                 frame_width: int = 1920, frame_height: int = 1080) -> List[RuleEvent]:
        """Evaluate all applicable rules against current tracks."""
        self._prune_cooldowns()
        events = []
        rules = self.cache.get_rules_for_camera(camera_id)

        for rule in rules:
            if not rule.get("is_enabled", True):
                continue

            rule_type = rule["rule_type"]
            for track in tracks:
                try:
                    event = self._evaluate_single(rule, track, camera_id, camera_role,
                                                   frame_width, frame_height)
                    if event:
                        # Check cooldown
                        cooldown_key = f"{rule['id']}:{track.local_track_id}"
                        cooldown_secs = rule.get("cooldown_seconds", 30)
                        if is_within_cooldown(self._cooldown_tracker.get(cooldown_key), cooldown_secs):
                            continue
                        self._cooldown_tracker[cooldown_key] = utc_now()
                        events.append(event)
                except Exception as e:
                    logger.error(f"Rule evaluation error: rule={rule.get('id')}, track={track.local_track_id}: {e}")

        return events

    def _evaluate_single(self, rule: dict, track: ActiveTrack, camera_id: uuid.UUID, camera_role: str,
                         frame_width: int = 1920, frame_height: int = 1080) -> Optional[RuleEvent]:
        """Evaluate a single rule against a single track."""
        rule_type = rule["rule_type"]

        if rule_type == "line_crossing":
            return self._eval_line_crossing(rule, track, camera_id, frame_width, frame_height)
        elif rule_type == "zone_dwell":
            return self._eval_zone_dwell(rule, track, camera_id)
        elif rule_type == "billing_interaction":
            return self._eval_billing_interaction(rule, track, camera_id, camera_role)
        elif rule_type == "queue_count":
            return self._eval_queue_count(rule, track, camera_id)
        elif rule_type == "possible_purchase":
            return self._eval_possible_purchase(rule, track, camera_id)
        elif rule_type == "restricted_zone":
            return self._eval_restricted_zone(rule, track, camera_id)
        return None

    def _eval_line_crossing(self, rule: dict, track: ActiveTrack, camera_id: uuid.UUID,
                            frame_width: int = 1920, frame_height: int = 1080) -> Optional[RuleEvent]:
        zone_id = rule.get("zone_id")
        if not zone_id or not track.prev_bbox or not track.bbox:
            return None
        zone = self.cache.zones.get(str(zone_id))
        if not zone or not zone.get("line_config"):
            return None
        line = line_from_json(zone["line_config"])
        if not line:
            return None
        prev_center = bbox_bottom_center(track.prev_bbox)
        curr_center = bbox_bottom_center(track.bbox)
        # Normalize to [0-1] range to match stored line coordinates
        prev_norm = (prev_center[0] / frame_width, prev_center[1] / frame_height)
        curr_norm = (curr_center[0] / frame_width, curr_center[1] / frame_height)
        direction = line_crossing_check(prev_norm, curr_norm, line[0], line[1])
        if direction:
            return RuleEvent(
                rule_id=uuid.UUID(rule["id"]), rule_type="line_crossing", camera_id=camera_id,
                zone_id=uuid.UUID(zone_id) if zone_id else None,
                track_session_id=track.track_session_id, person_identity_id=track.person_identity_id,
                event_type=f"line_crossing_{direction}", severity=rule.get("severity", "info"),
                description=f"Person crossed {zone.get('name','line')} ({direction})",
                metadata={"direction": direction, "zone_type": zone.get("zone_type")},
            )
        return None

    def _eval_zone_dwell(self, rule: dict, track: ActiveTrack, camera_id: uuid.UUID) -> Optional[RuleEvent]:
        zone_id = rule.get("zone_id")
        threshold = rule.get("dwell_threshold_seconds", 60)
        if not zone_id:
            return None
        dwell = track.dwell_seconds.get(str(zone_id), 0)
        if dwell >= threshold:
            return RuleEvent(
                rule_id=uuid.UUID(rule["id"]), rule_type="zone_dwell", camera_id=camera_id,
                zone_id=uuid.UUID(zone_id), track_session_id=track.track_session_id,
                person_identity_id=track.person_identity_id,
                event_type="zone_dwell_exceeded", severity=rule.get("severity", "warning"),
                description=f"Person dwelling in zone for {dwell:.0f}s (threshold={threshold}s)",
                metadata={"dwell_seconds": dwell, "threshold": threshold},
            )
        return None

    def _eval_billing_interaction(self, rule: dict, track: ActiveTrack, camera_id: uuid.UUID, camera_role: str) -> Optional[RuleEvent]:
        zone_id = rule.get("zone_id")
        if not zone_id or camera_role != "billing_counter":
            return None
        if str(zone_id) in track.current_zones:
            dwell = track.dwell_seconds.get(str(zone_id), 0)
            if dwell >= rule.get("dwell_threshold_seconds", 10):
                return RuleEvent(
                    rule_id=uuid.UUID(rule["id"]), rule_type="billing_interaction", camera_id=camera_id,
                    zone_id=uuid.UUID(zone_id), track_session_id=track.track_session_id,
                    person_identity_id=track.person_identity_id,
                    event_type="billing_interaction", severity="info",
                    description=f"Billing interaction detected ({dwell:.0f}s)",
                    metadata={"dwell_seconds": dwell},
                )
        return None

    def _eval_queue_count(self, rule: dict, track: ActiveTrack, camera_id: uuid.UUID) -> Optional[RuleEvent]:
        # Queue count is evaluated at the camera level, not per track
        # This is a placeholder - actual impl aggregates across all tracks
        return None

    def _eval_possible_purchase(self, rule: dict, track: ActiveTrack, camera_id: uuid.UUID) -> Optional[RuleEvent]:
        zone_id = rule.get("zone_id")
        if not zone_id:
            return None
        if str(zone_id) in track.current_zones:
            dwell = track.dwell_seconds.get(str(zone_id), 0)
            if dwell >= rule.get("dwell_threshold_seconds", 15):
                return RuleEvent(
                    rule_id=uuid.UUID(rule["id"]), rule_type="possible_purchase", camera_id=camera_id,
                    zone_id=uuid.UUID(zone_id), track_session_id=track.track_session_id,
                    person_identity_id=track.person_identity_id,
                    event_type="possible_purchase", severity="info",
                    description=f"Possible purchase activity ({dwell:.0f}s at product zone)",
                    metadata={"dwell_seconds": dwell},
                )
        return None

    def _eval_restricted_zone(self, rule: dict, track: ActiveTrack, camera_id: uuid.UUID) -> Optional[RuleEvent]:
        zone_id = rule.get("zone_id")
        if not zone_id:
            return None
        if str(zone_id) in track.current_zones:
            return RuleEvent(
                rule_id=uuid.UUID(rule["id"]), rule_type="restricted_zone", camera_id=camera_id,
                zone_id=uuid.UUID(zone_id), track_session_id=track.track_session_id,
                person_identity_id=track.person_identity_id,
                event_type="restricted_zone_intrusion", severity="alert",
                description="Person entered restricted zone",
                metadata={"zone_type": "restricted_zone"},
            )
        return None
